@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho

mainframe SMTTechnicalData

class "TechnicalData" as ID00000001 <<Submodel>> {
  +GeneralInformation : SubmodelElementCollection
  +ProductClassifications : SubmodelElementCollection
  +TechnicalProperties : SubmodelElementCollection
  +FurtherInformation : SubmodelElementCollection
  + : xs:string
}

class "GeneralInformation" as ID00000002 <<SubmodelElementCollection>> {
  +ManufacturerName : xs:string
  +ManufacturerLogo : File
  +ManufacturerProductDesignation : MultiLanguageProperty
  +ManufacturerArticleNumber : xs:string
  +ManufacturerOrderCode : xs:string
  +ProductImage : File
}

class "ProductClassifications" as ID00000003 <<SubmodelElementCollection>> {
  +ProductClassificationItem : SubmodelElementCollection
}

class "ProductClassificationItem" as ID00000004 <<SubmodelElementCollection>> {
  +ProductClassificationSystem : xs:string
  +ClassificationSystemVersion : xs:string
  +ProductClassId : xs:string
}

class "TechnicalProperties" as ID00000005 <<SubmodelElementCollection>> {
  +{arbitrary} : MultiLanguageProperty
  +{arbitrary} : xs:string
  +MainSection : SubmodelElementCollection
  +SubSection : SubmodelElementCollection
}

class "MainSection" as ID00000006 <<SubmodelElementCollection>> {
  +SubSection : SubmodelElementCollection
}

class "FurtherInformation" as ID00000007 <<SubmodelElementCollection>> {
  +TextStatement : MultiLanguageProperty
  +ValidDate : xs:date
}

ID00000001 *--  ID00000002 : "GeneralInformation"
ID00000003 *--  ID00000004 : "ProductClassificationItem"
ID00000001 *--  ID00000003 : "ProductClassifications"
ID00000005 *--  ID00000006 : "MainSection"
ID00000001 *--  ID00000005 : "TechnicalProperties"
ID00000001 *--  ID00000007 : "FurtherInformation"
@enduml
