@startuml
!theme plain
left to right direction
hide class circle
hide class methods
skinparam classAttributeIconSize 0
' skinparam linetype polyline
skinparam linetype ortho
mainframe SMT

mainframe SMT TechnicalData

class "TechnicalData" as ID00000001 <<Submodel>> {
  +GeneralInformation : SubmodelElementCollection
  +ProductClassifications : SubmodelElementCollection
  +TechnicalProperties : SubmodelElementCollection
  +FurtherInformation : SubmodelElementCollection
}

class "GeneralInformation" as ID00000002 <<SubmodelElementCollection>> {
  +ManufacturerName : xs:string
  +ManufacturerLogo : File
  +ManufacturerProductDesignation : MultiLanguageProperty
  +ManufacturerArticleNumber : xs:string
  +ManufacturerOrderCode : xs:string
  +ProductImage : File
}

class "ManufacturerName" as ID00000003 <<xs:string>> {
}

class "ManufacturerLogo" as ID00000004 <<File>> {
}

class "ManufacturerProductDesignation" as ID00000005 <<MultiLanguageProperty>> {
}

class "ManufacturerArticleNumber" as ID00000006 <<xs:string>> {
}

class "ManufacturerOrderCode" as ID00000007 <<xs:string>> {
}

class "ProductImage" as ID00000008 <<File>> {
}

class "ProductClassifications" as ID00000009 <<SubmodelElementCollection>> {
  +ProductClassificationItem : SubmodelElementCollection
}

class "ProductClassificationItem" as ID0000000A <<SubmodelElementCollection>> {
  +ProductClassificationSystem : xs:string
  +ClassificationSystemVersion : xs:string
  +ProductClassId : xs:string
}

class "ProductClassificationSystem" as ID0000000B <<xs:string>> {
}

class "ClassificationSystemVersion" as ID0000000C <<xs:string>> {
}

class "ProductClassId" as ID0000000D <<xs:string>> {
}

class "TechnicalProperties" as ID0000000E <<SubmodelElementCollection>> {
  +{arbitrary} : MultiLanguageProperty
  +{arbitrary} : xs:string
  +MainSection : SubmodelElementCollection
  +SubSection : SubmodelElementCollection
}

class "{arbitrary}" as ID0000000F <<MultiLanguageProperty>> {
}

class "{arbitrary}" as ID00000010 <<xs:string>> {
}

class "MainSection" as ID00000011 <<SubmodelElementCollection>> {
  +SubSection : SubmodelElementCollection
}

class "SubSection" as ID00000012 <<SubmodelElementCollection>> {
}

class "SubSection" as ID00000013 <<SubmodelElementCollection>> {
}

class "FurtherInformation" as ID00000014 <<SubmodelElementCollection>> {
  +TextStatement : MultiLanguageProperty
  +ValidDate : xs:date
}

class "TextStatement" as ID00000015 <<MultiLanguageProperty>> {
}

class "ValidDate" as ID00000016 <<xs:date>> {
}

ID00000002 *--  ID00000003 : "ManufacturerName"
ID00000002 *--  ID00000004 : "ManufacturerLogo"
ID00000002 *--  ID00000005 : "ManufacturerProductDesignation"
ID00000002 *--  ID00000006 : "ManufacturerArticleNumber"
ID00000002 *--  ID00000007 : "ManufacturerOrderCode"
ID00000002 *--  ID00000008 : "ProductImage"
ID00000001 *--  ID00000002 : "GeneralInformation"
ID0000000A *--  ID0000000B : "ProductClassificationSystem"
ID0000000A *--  ID0000000C : "ClassificationSystemVersion"
ID0000000A *--  ID0000000D : "ProductClassId"
ID00000009 *--  ID0000000A : "ProductClassificationItem"
ID00000001 *--  ID00000009 : "ProductClassifications"
ID0000000E *--  ID0000000F : "{arbitrary}"
ID0000000E *--  ID00000010 : "{arbitrary}"
ID00000011 *--  ID00000012 : "SubSection"
ID0000000E *--  ID00000011 : "MainSection"
ID0000000E *--  ID00000013 : "SubSection"
ID00000001 *--  ID0000000E : "TechnicalProperties"
ID00000014 *--  ID00000015 : "TextStatement"
ID00000014 *--  ID00000016 : "ValidDate"
ID00000001 *--  ID00000014 : "FurtherInformation"
@enduml
