/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines ModelingKind
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ModelingKind
    {
        /// <summary>
        /// Enum Template for value: Template
        /// </summary>
        [EnumMember(Value = "Template")]
        Template = 1,
        /// <summary>
        /// Enum Instance for value: Instance
        /// </summary>
        [EnumMember(Value = "Instance")]
        Instance = 2
    }
}
