/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Operation
    /// </summary>
    [DataContract]
    public partial class Operation : SubmodelElement, IEquatable<Operation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Operation" /> class.
        /// </summary>
        /// <param name="inoutputVariable">inoutputVariable.</param>
        /// <param name="inputVariable">inputVariable.</param>
        /// <param name="outputVariable">outputVariable.</param>
        public Operation(List<OperationVariable> inoutputVariable = default(List<OperationVariable>), List<OperationVariable> inputVariable = default(List<OperationVariable>), List<OperationVariable> outputVariable = default(List<OperationVariable>), List<EmbeddedDataSpecification> embeddedDataSpecifications = default(List<EmbeddedDataSpecification>), Reference semanticId = default(Reference), List<Constraint> qualifiers = default(List<Constraint>), ModelingKind kind = default(ModelingKind)) : base(embeddedDataSpecifications, semanticId, qualifiers, kind)
        {
            this.InoutputVariable = inoutputVariable;
            this.InputVariable = inputVariable;
            this.OutputVariable = outputVariable;
        }

        /// <summary>
        /// Gets or Sets InoutputVariable
        /// </summary>
        [DataMember(Name = "inoutputVariable", EmitDefaultValue = false)]
        public List<OperationVariable> InoutputVariable { get; set; }

        /// <summary>
        /// Gets or Sets InputVariable
        /// </summary>
        [DataMember(Name = "inputVariable", EmitDefaultValue = false)]
        public List<OperationVariable> InputVariable { get; set; }

        /// <summary>
        /// Gets or Sets OutputVariable
        /// </summary>
        [DataMember(Name = "outputVariable", EmitDefaultValue = false)]
        public List<OperationVariable> OutputVariable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Operation {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  InoutputVariable: ").Append(InoutputVariable).Append("\n");
            sb.Append("  InputVariable: ").Append(InputVariable).Append("\n");
            sb.Append("  OutputVariable: ").Append(OutputVariable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Operation);
        }

        /// <summary>
        /// Returns true if Operation instances are equal
        /// </summary>
        /// <param name="input">Instance of Operation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Operation input)
        {
            if (input == null)
                return false;

            return base.Equals(input) &&
                (
                    this.InoutputVariable == input.InoutputVariable ||
                    this.InoutputVariable != null &&
                    input.InoutputVariable != null &&
                    this.InoutputVariable.SequenceEqual(input.InoutputVariable)
                ) && base.Equals(input) &&
                (
                    this.InputVariable == input.InputVariable ||
                    this.InputVariable != null &&
                    input.InputVariable != null &&
                    this.InputVariable.SequenceEqual(input.InputVariable)
                ) && base.Equals(input) &&
                (
                    this.OutputVariable == input.OutputVariable ||
                    this.OutputVariable != null &&
                    input.OutputVariable != null &&
                    this.OutputVariable.SequenceEqual(input.OutputVariable)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.InoutputVariable != null)
                    hashCode = hashCode * 59 + this.InoutputVariable.GetHashCode();
                if (this.InputVariable != null)
                    hashCode = hashCode * 59 + this.InputVariable.GetHashCode();
                if (this.OutputVariable != null)
                    hashCode = hashCode * 59 + this.OutputVariable.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
