/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PackageDescription
    /// </summary>
    [DataContract]
    public partial class PackageDescription : IEquatable<PackageDescription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PackageDescription" /> class.
        /// </summary>
        /// <param name="aasIds">aasIds.</param>
        /// <param name="packageId">packageId.</param>
        public PackageDescription(List<string> aasIds = default(List<string>), string packageId = default(string))
        {
            this.AasIds = aasIds;
            this.PackageId = packageId;
        }

        /// <summary>
        /// Gets or Sets AasIds
        /// </summary>
        [DataMember(Name = "aasIds", EmitDefaultValue = false)]
        public List<string> AasIds { get; set; }

        /// <summary>
        /// Gets or Sets PackageId
        /// </summary>
        [DataMember(Name = "packageId", EmitDefaultValue = false)]
        public string PackageId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PackageDescription {\n");
            sb.Append("  AasIds: ").Append(AasIds).Append("\n");
            sb.Append("  PackageId: ").Append(PackageId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PackageDescription);
        }

        /// <summary>
        /// Returns true if PackageDescription instances are equal
        /// </summary>
        /// <param name="input">Instance of PackageDescription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PackageDescription input)
        {
            if (input == null)
                return false;

            return
                (
                    this.AasIds == input.AasIds ||
                    this.AasIds != null &&
                    input.AasIds != null &&
                    this.AasIds.SequenceEqual(input.AasIds)
                ) &&
                (
                    this.PackageId == input.PackageId ||
                    (this.PackageId != null &&
                    this.PackageId.Equals(input.PackageId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AasIds != null)
                    hashCode = hashCode * 59 + this.AasIds.GetHashCode();
                if (this.PackageId != null)
                    hashCode = hashCode * 59 + this.PackageId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
