/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PolicyAdministrationPoint
    /// </summary>
    [DataContract]
    public partial class PolicyAdministrationPoint : IEquatable<PolicyAdministrationPoint>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyAdministrationPoint" /> class.
        /// </summary>
        /// <param name="externalAccessControl">externalAccessControl (required).</param>
        /// <param name="localAccessControl">localAccessControl.</param>
        public PolicyAdministrationPoint(bool? externalAccessControl = default(bool?), AccessControl localAccessControl = default(AccessControl))
        {
            // to ensure "externalAccessControl" is required (not null)
            if (externalAccessControl == null)
            {
                throw new InvalidDataException("externalAccessControl is a required property for PolicyAdministrationPoint and cannot be null");
            }
            else
            {
                this.ExternalAccessControl = externalAccessControl;
            }
            this.LocalAccessControl = localAccessControl;
        }

        /// <summary>
        /// Gets or Sets ExternalAccessControl
        /// </summary>
        [DataMember(Name = "externalAccessControl", EmitDefaultValue = false)]
        public bool? ExternalAccessControl { get; set; }

        /// <summary>
        /// Gets or Sets LocalAccessControl
        /// </summary>
        [DataMember(Name = "localAccessControl", EmitDefaultValue = false)]
        public AccessControl LocalAccessControl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PolicyAdministrationPoint {\n");
            sb.Append("  ExternalAccessControl: ").Append(ExternalAccessControl).Append("\n");
            sb.Append("  LocalAccessControl: ").Append(LocalAccessControl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PolicyAdministrationPoint);
        }

        /// <summary>
        /// Returns true if PolicyAdministrationPoint instances are equal
        /// </summary>
        /// <param name="input">Instance of PolicyAdministrationPoint to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PolicyAdministrationPoint input)
        {
            if (input == null)
                return false;

            return
                (
                    this.ExternalAccessControl == input.ExternalAccessControl ||
                    (this.ExternalAccessControl != null &&
                    this.ExternalAccessControl.Equals(input.ExternalAccessControl))
                ) &&
                (
                    this.LocalAccessControl == input.LocalAccessControl ||
                    (this.LocalAccessControl != null &&
                    this.LocalAccessControl.Equals(input.LocalAccessControl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalAccessControl != null)
                    hashCode = hashCode * 59 + this.ExternalAccessControl.GetHashCode();
                if (this.LocalAccessControl != null)
                    hashCode = hashCode * 59 + this.LocalAccessControl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
