/* 
 * DotAAS Part 2 | HTTP/REST | Entire Interface Collection
 *
 * The entire interface collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: Final-Draft
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PolicyDecisionPoint
    /// </summary>
    [DataContract]
    public partial class PolicyDecisionPoint : IEquatable<PolicyDecisionPoint>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PolicyDecisionPoint" /> class.
        /// </summary>
        /// <param name="externalPolicyDecisionPoints">externalPolicyDecisionPoints (required).</param>
        public PolicyDecisionPoint(bool? externalPolicyDecisionPoints = default(bool?))
        {
            // to ensure "externalPolicyDecisionPoints" is required (not null)
            if (externalPolicyDecisionPoints == null)
            {
                throw new InvalidDataException("externalPolicyDecisionPoints is a required property for PolicyDecisionPoint and cannot be null");
            }
            else
            {
                this.ExternalPolicyDecisionPoints = externalPolicyDecisionPoints;
            }
        }

        /// <summary>
        /// Gets or Sets ExternalPolicyDecisionPoints
        /// </summary>
        [DataMember(Name = "externalPolicyDecisionPoints", EmitDefaultValue = false)]
        public bool? ExternalPolicyDecisionPoints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PolicyDecisionPoint {\n");
            sb.Append("  ExternalPolicyDecisionPoints: ").Append(ExternalPolicyDecisionPoints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PolicyDecisionPoint);
        }

        /// <summary>
        /// Returns true if PolicyDecisionPoint instances are equal
        /// </summary>
        /// <param name="input">Instance of PolicyDecisionPoint to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PolicyDecisionPoint input)
        {
            if (input == null)
                return false;

            return
                (
                    this.ExternalPolicyDecisionPoints == input.ExternalPolicyDecisionPoints ||
                    (this.ExternalPolicyDecisionPoints != null &&
                    this.ExternalPolicyDecisionPoints.Equals(input.ExternalPolicyDecisionPoints))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExternalPolicyDecisionPoints != null)
                    hashCode = hashCode * 59 + this.ExternalPolicyDecisionPoints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
