name: build-solution

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
 
      - name: Check the commit message(s)
        uses: mristin/opinionated-commit-message@v1.0.4

      - name: Check licenses
        working-directory: src
        run: powershell .\CheckLicenses.ps1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0
        with:
          vs-version: 15

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      - name: Install Microsoft .NET Compilers
        run: nuget install Microsoft.NET.Compilers -Version 2.10.0 -OutputDirectory tools

      - name: Install Nunit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory tools

      - name: Install Nunit Project Loader
        run: nuget install NUnit.Extension.NUnitProjectLoader -Version 3.6.0 -OutputDirectory tools

      - name: Install OpenCover
        run: nuget install OpenCover -Version 4.7.922 -OutputDirectory tools

      - name: Install ReportGenerator
        run: nuget install ReportGenerator -Version 4.6.0 -OutputDirectory tools

      - name: Install .NET core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - name: Restore NuGet Packages
        working-directory: src
        run: nuget restore AasxPackageExplorer.sln

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 3.3.111304

      - name: Setup ReSharper Command Line Tools
        uses: goit/setup-resharper@v1.0.0
        with:
          version: '2020.1.2'	

      - name: Check format
        working-directory: src
        run: powershell .\CheckFormat.ps1

      - name: Build
        working-directory: src
        run: powershell .\Build.ps1

      - name: Test
        working-directory: src
        run: powershell .\Test.ps1

      - name: Inspect code
        working-directory: src
        run: powershell .\InspectCode.ps1

